title: "The Golden Dragon Bistro"
email: "orders@goldendragonbistro.example"
description: "Authentic American-Chinese cuisine crafted fresh. Order online for pickup or delivery."
baseurl: "" 
url: "https://khisal786.github.io/GoldenDragonBistro/"

# Enable Sass processing
sass:
  style: compressed
  sass_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
